---

- name: Start/enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfs_client_services|default([]) }}"

- name: Start/enable kerberos services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfs_client_services_krb5|default([]) }}"
  when: nfs_krb5|bool

- name: set selinux bool for using share as home dir
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes
  when: nfs_home_dir|bool

- name: Get stat of all mountpoints
  stat:
    path: "{{ item.target }}"
  loop: "{{ nfs_mounts }}"
  register: _mp

- name: Ensure mount path exists
  file:
    path: "{{ item.item.target }}"
    state: directory
    mode: "0755"
  loop: "{{ _mp.results }}"
  loop_control:
    label:
      - "{{ item.item.target }}"
  when: not item.stat.exists

- name: Mount NFS shares
  mount:
    path: '{{ item.target }}'
    src: '{{ item.src }}'
    fstype: nfs
    opts: '{{ item.options }}'
    state: mounted
  loop: "{{ nfs_mounts }}"
