---

- name: Configure NFS
  lineinfile:
    path: /etc/default/nfs-kernel-server
    line: "NEED_SVCGSSD={{ 'yes' if nfs_krb5|bool else 'no' }}"
    regexp: "NEED_SVCGSSD=."
  notify: Restart nfs
  when:
    - ansible_os_family == 'Debian'

- name: Open firewall ports (firewalld)
  include_role:
    name: firewalld
    tasks_from: rules.yml
  vars:
    firewalld_rules: "{{ nfs_server_firewall_ports }}"
  when: ansible_os_family == 'RedHat'

- name: Open firewall ports (ufw)
  include_role:
    name: ufw
    tasks_from: rules.yml
  vars:
    ufw_rules: "{{ nfs_server_firewall_ports }}"
  when: ansible_os_family == 'Debian'

- name: Start/enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfs_server_services }}"

- name: Start/enable kerberos services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfs_server_services_krb5 }}"
  when: nfs_krb5|bool
