---

- name: Install NFS server packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nfs_server_packages }}"

- name: Install NFS server with kerberos packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ nfs_server_packages_krb5 }}"

- name: Start services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ nfs_server_services }}"
