---

- name: Load variables based on OS type
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "family-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "family-{{ ansible_os_family }}.yml"
        - default.yml
      paths:
        - 'vars'

- name: Combine firewall rules for v3 + v4
  ansible.builtin.set_fact:
    nfs_server_firewall_ports: "{{ nfs_v3_server_firewall_ports + nfs_v4_server_firewall_ports }}"
  when: nfs_v3 | bool

- name: Use firewall rules v4 only
  ansible.builtin.set_fact:
    nfs_server_firewall_ports: "{{ nfs_v4_server_firewall_ports }}"
  when: not nfs_v3 | bool

- name: NFS server
  when: nfs_server
  block:
    - name: Include install-server.yml
      ansible.builtin.include_tasks: install-server.yml
    - name: Include config-server-{{ ansible_os_family }}.yml  # noqa name[template]
      ansible.builtin.include_tasks: config-server-{{ ansible_os_family }}.yml
    - name: Include exports.yml
      ansible.builtin.include_tasks: exports.yml

- name: NFS client
  when: nfs_client
  block:
    - name: Include install-client.yml
      ansible.builtin.include_tasks: install-client.yml
    - name: Include config-client.yml
      ansible.builtin.include_tasks: config-client.yml
