---

- name: Converge
  hosts: all
  become: true
  vars:
    nfs_v3: true
    nfs_v4: false
    __nfs_server: "{{ groups['nfs_servers'] | first }}"
    __nfs_client: "{{ groups['nfs_clients'] | first }}"
    export_path: /export/test
  tasks:

    - name: Create path to export
      ansible.builtin.file:
        path: "{{ export_path }}"
        state: directory
        mode: "0755"

    - name: Setup NFS server
      ansible.builtin.include_role:
        name: ansible-role-nfs
      vars:
        nfs_server: true
        nfs_exports:
          - { path: "{{ export_path }}", clients: "{{ [ hostvars[__nfs_client]['ansible_default_ipv4']['address'] ] }}", options: 'rw,sync,no_root_squash' }
      when: inventory_hostname in groups['nfs_servers']

    - name: Setup NFS client
      ansible.builtin.include_role:
        name: ansible-role-nfs
      vars:
        nfs_server: false
        nfs_mounts:
          - { src: "{{ hostvars[__nfs_server]['ansible_default_ipv4']['address'] }}:{{ export_path }}", target: /mnt, type: 'nfs', options: 'rw,sync' }
      when: inventory_hostname in groups['nfs_clients']
