---

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: nfs-server-${MOLECULE_DISTRO:-centos8}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
# important to make NFS export work
      - /tmp/nfs:/srv:rw
    privileged: true
    pre_build_image: true
  - name: nfs-client-${MOLECULE_DISTRO:-centos8}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      nfs-server-${MOLECULE_DISTRO:-centos8}:
        nfs_firewall: ${nfs_firewall:-true}
        nfs_v3: true
        nfs_v4: true
        nfs_server: true
        nfs_client: false
        nfs_exports:
          - path: /srv
            clients: "*"
            options: "rw,sync"
      nfs-client-${MOLECULE_DISTRO:-centos8}:
        nfs_firewall: ${nfs_firewall:-true}
        nfs_v3: true
        nfs_v4: true
        nfs_mounts:
          - src: "{{ hostvars['nfs-server-${MOLECULE_DISTRO:-centos8}']['ansible_default_ipv4']['address'] }}:/srv"
            target: /mnt
            options: vers=3,sync
scenario:
  name: default
verifier:
  name: ansible
