---
- name: Converge
  hosts: all
  tasks:

    - block:

      - name: Update APT cache
        apt:
          update_cache: yes
          cache_valid_time: 1
        become: yes

      - name: Install ufw
        apt:
          name: ufw
          state: present

      - name: Activate ufw
        ufw:
          state: enabled

      - name: Start firewalld
        service:
          name: ufw
          state: started
          enabled: yes

      when: ansible_os_family == 'Debian'

    - block:

      - name: Install firewalld
        yum:
          name: firewalld
          state: present

      - name: Start firewalld
        service:
          name: firewalld
          state: started
          enabled: yes

      when: ansible_os_family == 'RedHat'


    - name: "Include ansible-role-nfs"
      include_role:
        name: "ansible-role-nfs"
